export const PEOPLE_LOAD_START = 'PEOPLE_LOAD_START';
export const PEOPLE_LOADED = 'PEOPLE_LOADED';
export const PEOPLE_LOAD_FAILED = 'PEOPLE_LOAD_FAILED';

export const FILMS_LOAD_START = 'FILMS_LOAD_START';
export const FILMS_LOADED = 'FILMS_LOADED';
export const FILMS_LOAD_FAILED = 'FILMS_LOAD_FAILED';

export const SPECIES_LOAD_START = 'SPECIES_LOAD_START';
export const SPECIES_LOADED = 'SPECIES_LOADED';
export const SPECIES_LOAD_FAILED = 'SPECIES_LOAD_FAILED';

export const PERSON_LOAD_START = 'PERSON_LOAD_START';
export const PERSON_LOADED = 'PERSON_LOADED';
export const PERSON_LOAD_FAILED = 'PERSON_LOAD_FAILED';

export const PERSON_DELETED = 'PERSON_DELETED';

